name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
#        os: [macos-10.15, macos-11.0, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        os: [macos-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Initialize Package Manager (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get update -qq

    - name: Initialize Package Manager (Mac)
      if: startsWith(matrix.os, 'macos')
      run: brew update

    - name: Install GNU Octave (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install -y -qq libopenblas-dev liboctave-dev octave
        octave-cli --no-gui --eval ver
        echo "OCTAVE_VER=`octave-cli --no-gui --eval "fprintf('%s', ver('octave').Version)"`" >> $GITHUB_ENV

    - name: Install GNU Octave (Mac)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install octave
        octave-cli --no-gui --eval ver
        echo "OCTAVE_VER=`octave-cli --no-gui --eval "fprintf('%s', ver('octave').Version)"`" >> $GITHUB_ENV

    - name: Build/Install SeDuMi
      run: |
        git clone --depth=1 https://github.com/sqlp/sedumi.git $HOME/sedumi
        cd $HOME/sedumi
        mv vec.m vec.m.disabled
        octave-cli --no-gui --eval "install_sedumi('-rebuild'); savepath"

    - name: Build/Install SDPT3
      run: |
        git clone --depth=1 https://github.com/sqlp/sdpt3.git $HOME/sdpt3
        cd $HOME/sdpt3
        octave-cli --no-gui --eval "install_sdpt3('-rebuild'); savepath"

    - name: Install YALMIP
      run: |
        git clone --depth=1 -b R20180817 https://github.com/yalmip/YALMIP.git $HOME/yalmip
        octave-cli --no-gui --eval "addpath(genpath('$HOME/yalmip', '.git', 'o_win', 'dev'), '-end'); savepath"

    - name: Install MATPOWER
      run: |
        git clone --depth=1 https://github.com/MATPOWER/matpower.git $HOME/matpower
        octave-cli --no-gui -p $HOME/matpower --eval "install_matpower(1,1,1)"
        octave-cli --no-gui --eval mpver
        echo "TEST_PATH=${GITHUB_WORKSPACE}/lib:${GITHUB_WORKSPACE}/lib/t" >> $GITHUB_ENV

    - name: Test SeDuMi availability, print version number
      run:  |
        octave-cli --no-gui --eval "if ~have_feature('sedumi'), exit(1); end"
        octave-cli --no-gui --eval "x = sedumi([1 1], 1, [1;2]);"

    - name: Test SDPT3 availability, print version number
      run:  |
        octave-cli --no-gui --eval "if ~have_feature('sdpt3'), exit(1); end"
        octave-cli --no-gui --eval "help sdpt3"

    - name: Test YALMIP availability, print version number
      run:  |
        octave-cli --no-gui --eval "if ~have_feature('yalmip'), exit(1); end"
        octave-cli --no-gui --eval "yalmip('version')"

    - name: Test SDP_PF
      run: |
        octave-cli --no-gui -p $TEST_PATH --eval mpver
        octave-cli --no-gui -p $TEST_PATH --eval  "test_sdp_pf(1,1)"
